### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by at15** [dyweb/bmFu#12]
I wrote a style guide in https://github.com/dyweb/bmFu/blob/master/doc/style.md

but now seems we have bifurcated. 

@arrowrowe  use `countAll` for model methods instead of `count_all`

I think it's still not too late to have this discussion.

Advantage of snake_case

1. it follows the old standard in Codeignitor based project
2. it's more explicit than camelCase

Advantage of CamelCase

1. it follows modern php standard

@arrowrowe @ComMouse @swaylq @xsfour 

so let's have a vote, :+1: for snake_case, :-1:  for camelCase

**Comment by at15** [comment]
:-1:  I think we should move on and remove usage for Codeingitor step by step. including its style guide.

**Comment by ComMouse** [comment]
@at15 The camelCase in bmFu is unified by me.... because I've seen both countAll and get_where in one class...

**Comment by at15** [comment]
@ComMouse  i don't think we need to do that, though some framework may have this as a built in feature, i think its better to leave it to user , besides MySQL is not case sensitive in windows ...

**Comment by ComMouse** [comment]
Well, leave it as same as what is done in js.

**Comment by at15** [comment]
@ComMouse what have we done in js?.... mix snake_case and camelCase everywhere?....

**Comment by arrowrowe** [comment]
:-1:

**Comment by swaylq** [comment]
:-1:
