### ISSUE TITLE
filter user input

### ISSUE THREAD

**Issue by at15** [dyweb/bmFu#2]
-  [x]  selected fields eg:   act?select=name,desc,create_time
 -  [x]  order by eg: act?order=+create_time-member_count
 -  [x]  where eg: act?type=1

allow using the model to filter the user input, instead of write it in every controller

**Comment by at15** [comment]
@arrowrowe  do you have example in doc or in test? BTW: i think we need to use guzzle to test it. see 
#5

**Comment by arrowrowe** [comment]
@at15 Yes. Some tests, see [OrmTest.php](https://github.com/dyweb/bmFu/blob/master/tests/OrmTest.php)'s `testOrder`, `testWhere`, `testPage`, `testGetWhere`.

**Comment by at15** [comment]
@arrowrowe  ok got. you are just passing array so no need to use guzzle for http request.
