### ISSUE TITLE
soft delete

### ISSUE THREAD

**Issue by xsfour** [dyweb/bmFu#8]
- [x]  hard delete
- [x]  soft delete

use trait?

**Comment by ComMouse** [comment]
@at15 Here is a problem when deleting: If we get a ORM object whose id = 6 in one model and delete another one whose id is also 6 in another model, then the data of two objects are not equal which may cause conflicts. Do we need yo synchronize all the ORM objects which hold the same id?

**Comment by at15** [comment]
@ComMouse  I don't think we need to do that, but i think php has method to find all instances of certain class. because when you use `var_dump` you will see a `object#i` where `i` is the number for this instance

**Comment by at15** [comment]
@ComMouse got. @arrowrowe  code review?
