### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by at15** [dyweb/bmFu#9]
1. generate standard output for validation error
2. return 400 because it is client error.
3. better have angularjs integration so front end will have little work to do. we can extend $http to another service.

you can use ilex's, but i suggest consider the one used in laravel in axws and the current one we are using in tongqu's `tq` folder, the one in `dywiki` is the newer version for that.

**Comment by arrowrowe** [comment]
OK.

**Comment by arrowrowe** [comment]
See [Document for Ilex\Lib\Validate](https://github.com/arrowrowe/ilex/wiki/Document-for-Ilex%5CLib%5CValidate) for details.

**Comment by at15** [comment]
@arrowrowe  变成一个composer的package吧?这样方便一点
